<?php

declare(strict_types=1);

$source = file_get_contents(__DIR__ . '/../crates/syntax/src/cst/node.rs');
if ($source === false) {
    throw new RuntimeException('Unable to read the Rust NodeKind declaration.');
}

$prefix = 'pub enum NodeKind {';
$bodyStart = strpos($source, $prefix);
if ($bodyStart === false) {
    throw new RuntimeException('Unable to locate the Rust NodeKind declaration.');
}

$bodyStart += strlen($prefix);
$bodyEnd = strpos($source, "\n}", $bodyStart);
if ($bodyEnd === false) {
    throw new RuntimeException('Unable to locate the end of the Rust NodeKind declaration.');
}

$body = substr($source, $bodyStart, $bodyEnd - $bodyStart);
$names = [];
foreach (explode("\n", $body) as $line) {
    $name = rtrim(trim($line), ',');
    if (preg_match('/^[A-Za-z][A-Za-z0-9]*$/', $name) === 1) {
        $names[] = $name;
    }
}

if ($names === []) {
    throw new RuntimeException('The Rust NodeKind declaration contains no variants.');
}

$cases = '';
foreach ($names as $name) {
    $case = $name === 'Class' ? 'Class_' : $name;
    $cases .= "    case {$case} = '{$name}';\n";
}

$php =
    "<?php\n\n"
    . "declare(strict_types=1);\n\n"
    . "namespace Mago\\Sdk\\Syntax;\n\n"
    . "/**\n"
    . " * Stable names of concrete syntax tree nodes exposed to extensions.\n"
    . " *\n"
    . " * This file is generated by `just regen-sdk-node-kinds`.\n"
    . " *\n"
    . " * @api\n"
    . " * @mago-expect lint:too-many-enum-cases\n"
    . " */\n"
    . "enum NodeKind: string\n"
    . "{\n"
    . $cases
    . "}\n";

$written = file_put_contents(__DIR__ . '/../composer/src/Sdk/Syntax/NodeKind.php', $php);
if ($written === false) {
    throw new RuntimeException('Unable to write the PHP NodeKind declaration.');
}
